version: '3.8'

services:
  db:
    build: ./mysql
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: ETL
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    
  adminer:
    image: adminer                 # Image officielle d'Adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"                # Expose Adminer sur le port 8080

volumes:
  mysql_data: